/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_index"];
        put?: never;
        post: operations["AppController_store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar saldo da conta do usuário autenticado */
        get: operations["AccountController_balance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar transferências enviadas e recebidas */
        get: operations["TransferController_list"];
        put?: never;
        /** Realizar transferência para outra conta MiniBank */
        post: operations["TransferController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todas as solicitações de empréstimo (gerente) */
        get: operations["LoanController_list"];
        put?: never;
        /** Solicitar empréstimo */
        post: operations["LoanController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loans/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Aprovar ou recusar solicitação de empréstimo (gerente) */
        patch: operations["LoanController_review"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AppController_store: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AccountController_balance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saldo retornado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accountNumber: number;
                        balance: number;
                    };
                };
            };
            /** @description Conta não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransferController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de transferências */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        transfers: {
                            transferId: string;
                            /** @enum {string} */
                            direction: "SENT" | "RECEIVED";
                            otherAccountNumber: number;
                            amount: number;
                            /** Format: date-time */
                            occurredAt: string;
                        }[];
                    };
                };
            };
            /** @description Conta não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransferController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Número da conta destino
                     * @example 2
                     */
                    toAccountNumber: number;
                    /**
                     * @description Valor em centavos
                     * @example 1000
                     */
                    amount: number;
                };
            };
        };
        responses: {
            /** @description Transferência realizada com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        transferId: string;
                        fromBalance: number;
                        toBalance: number;
                    };
                };
            };
            /** @description Saldo insuficiente ou valor inválido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conta destino não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LoanController_list: {
        parameters: {
            query?: {
                /** @description Filtrar por status */
                status?: "PENDING" | "ACEITO" | "RECUSADO";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de solicitações de empréstimo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        accountNumber: number;
                        customerName: string;
                        amount: number;
                        reason: string;
                        /** @enum {string} */
                        status: "PENDING" | "ACEITO" | "RECUSADO";
                        /** Format: date-time */
                        requestedAt: string;
                    }[];
                };
            };
            /** @description Acesso restrito a gerentes */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LoanController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Valor em centavos
                     * @example 50000
                     */
                    amount: number;
                    /**
                     * @description Motivo do empréstimo
                     * @example Reforma da casa
                     */
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Empréstimo solicitado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        amount: number;
                        reason: string;
                        status: string;
                        /** Format: date-time */
                        requestedAt: string;
                    };
                };
            };
            /** @description Valor ou motivo inválido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conta não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LoanController_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID da solicitação de empréstimo */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Decisão do gerente
                     * @enum {string}
                     */
                    decision: "APPROVE" | "REJECT";
                };
            };
        };
        responses: {
            /** @description Empréstimo revisado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        status: string;
                        newBalance: number;
                    };
                };
            };
            /** @description Solicitação não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Solicitação já foi revisada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
